# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-17 17:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='Город')),
            ],
            options={
                'verbose_name': 'Город',
                'verbose_name_plural': 'Города',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='Страна')),
            ],
            options={
                'verbose_name': 'Страна',
                'verbose_name_plural': 'Страны',
            },
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house', models.CharField(max_length=6, unique=True, verbose_name='Дом')),
                ('building', models.CharField(blank=True, max_length=4, null=True, unique=True, verbose_name='Строение')),
            ],
            options={
                'verbose_name': 'Дом',
                'verbose_name_plural': 'Дома',
            },
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apartments', models.CharField(blank=True, max_length=6, null=True, unique=True, verbose_name='Квартира')),
                ('latitude', models.CharField(blank=True, max_length=16, null=True, unique=True, verbose_name='Широта')),
                ('longitude', models.CharField(blank=True, max_length=16, null=True, unique=True, verbose_name='Долгота')),
                ('description', models.TextField(blank=True, max_length=64, null=True, verbose_name='Описание')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Addresses.City', verbose_name='Город')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Addresses.Country', verbose_name='Страна')),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Addresses.House', verbose_name='Дом')),
            ],
            options={
                'verbose_name': 'Место',
                'verbose_name_plural': 'Места',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='Регион')),
            ],
            options={
                'verbose_name': 'Регион',
                'verbose_name_plural': 'Регионы',
            },
        ),
        migrations.CreateModel(
            name='Street',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='Улица')),
            ],
            options={
                'verbose_name': 'Улица',
                'verbose_name_plural': 'Улицы',
            },
        ),
        migrations.AddField(
            model_name='place',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Addresses.Region', verbose_name='Регион'),
        ),
        migrations.AddField(
            model_name='place',
            name='street',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Addresses.Street', verbose_name='Улица'),
        ),
    ]
