# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-25 13:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_auto_20170425_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='', upload_to='', verbose_name='avatars/'),
        ),
    ]
