# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-25 15:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0004_auto_20170425_1802'),
    ]

    operations = [
        migrations.CreateModel(
            name='Languagecode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=5)),
            ],
            options={
                'verbose_name': 'Код языка',
                'verbose_name_plural': 'Коды языков',
            },
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Профиль пользователя', 'verbose_name_plural': 'Профили пользователей'},
        ),
        migrations.AddField(
            model_name='profile',
            name='languagecode',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='Users.Languagecode'),
        ),
    ]
