# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-25 15:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0005_auto_20170425_1844'),
    ]

    operations = [
        migrations.AddField(
            model_name='languagecode',
            name='name',
            field=models.CharField(default='', max_length=16),
        ),
    ]
