# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-21 12:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0005_auto_20170421_1323'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='fax_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, verbose_name='Факс'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(default='', max_length=128, verbose_name='Контактный телефон'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активный'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_admin',
            field=models.BooleanField(default=False, verbose_name='Админ'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_clinic',
            field=models.BooleanField(default=False, verbose_name='Клиника'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_moder',
            field=models.BooleanField(default=False, verbose_name='Модератор'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_owner',
            field=models.BooleanField(default=False, verbose_name='Владелец'),
        ),
        migrations.AlterField(
            model_name='user',
            name='location',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='Addresses.Place', verbose_name='Место'),
        ),
    ]
