# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-25 15:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0006_languagecode_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='languagecode',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='Users.LanguageCode'),
        ),
    ]
