# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-21 12:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0006_auto_20170421_1500'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='avatars/nopic.jpg', upload_to='avatars/'),
        ),
    ]
