# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-21 10:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pets', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pet',
            options={'verbose_name': 'Животные', 'verbose_name_plural': 'Животные'},
        ),
        migrations.AlterModelOptions(
            name='pettype',
            options={'verbose_name': 'Тип животного', 'verbose_name_plural': 'Типы животных'},
        ),
        migrations.AlterField(
            model_name='pet',
            name='chip_id',
            field=models.CharField(max_length=16, unique=True, verbose_name='ID чипа'),
        ),
    ]
