# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-21 13:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pets', '0002_auto_20170421_1321'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='image',
            field=models.ImageField(default='/pets/nopet.jpg', upload_to='pets/'),
        ),
    ]
