# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-21 15:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pets', '0003_pet_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Petcolor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, unique=True, verbose_name='Окрас')),
            ],
            options={
                'verbose_name': 'Окрас',
                'verbose_name_plural': 'Окрас',
            },
        ),
    ]
