# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-21 16:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Pets', '0004_petcolor'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='birthday',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата рождения'),
        ),
        migrations.AddField(
            model_name='pet',
            name='registrationdate',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата регистрации'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pet',
            name='special',
            field=models.TextField(blank=True, null=True, verbose_name='Особые приметы'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='breed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pets.PetBreed', verbose_name='Порода'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='image',
            field=models.ImageField(default='/pets/nopet.jpg', upload_to='pets/', verbose_name='Аватар'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Хозяин'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='registrator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Регистратор'),
        ),
    ]
