# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-21 16:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pets', '0005_auto_20170421_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='registrationdate',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Дата регистрации'),
        ),
    ]
